using Syntaxsmith.CSharp.Configuration;

namespace Syntaxsmith.CSharp;

public class ClassBuilder : NamespaceBuilder<ClassBuilder>
{
    public ClassBuilder(string className, SyntaxContext context, bool enableNullable = true)
        : base(className, context)
    {
        AddLine("// <autogenerated/>");
        AddLine("#nullable " + (enableNullable ? "enable" : "disable"));

        XmlDocs = new XmlDocsBuilder(Context);
    }

    public XmlDocsBuilder XmlDocs { get; }


    public ClassBuilder Open(Action<ClassConfigurationBuilder>? configAction = null)
    {
        var builder = new ClassConfigurationBuilder(TypeName);

        if (configAction is not null)
        {
            configAction(builder);
        }

        builder.AppendToContext(Context);

        BlockOpen();
        return this;
    }
}