using Syntaxsmith.CSharp.Configuration;

namespace Syntaxsmith.CSharp;

public class ClassBuilder : NamespaceBuilder<ClassBuilder>
{
    public ClassBuilder(string className, SyntaxContext context, bool enableNullable = true)
        : base(className, context)
    {
        AddCommentLine("<autogenerated/>");       
        AddDirective(enableNullable ? PreprocessorDirective.NullableEnable : PreprocessorDirective.NullableDisable);
    }

    public ClassBuilder Open(Action<ClassConfigurationBuilder>? configAction = null)
    {
        return ClassOpen(TypeName, configAction);
    }
}