using Syntaxsmith.CSharp.Configuration;

namespace Syntaxsmith.CSharp;

public class EnumBuilder : NamespaceBuilder<StructBuilder>
{
    public EnumBuilder(string enumName, SyntaxContext context, bool enableNullable = true)
        : base(enumName, context)
    {
        AddLine("// <autogenerated/>");
        AddLine("#nullable " + (enableNullable ? "enable" : "disable"));

        XmlDocs = new XmlDocsBuilder(Context);
    }

    public XmlDocsBuilder XmlDocs { get; }

    public EnumBuilder Open(Action<StructConfigurationBuilder>? configAction = null)
    {
        var builder = new StructConfigurationBuilder(TypeName);

        if (configAction is not null)
        {
            configAction(builder);
        }

        builder.AppendToContext(Context);

        BlockOpen();
        return this;
    }
}