using Syntaxsmith.CSharp.Configuration;

namespace Syntaxsmith.CSharp;

public class EnumBuilder : NamespaceBuilder<EnumBuilder>
{
    public EnumBuilder(string enumName, SyntaxContext context, bool enableNullable = true)
        : base(enumName, context)
    {
        AddCommentLine("<autogenerated/>");
        AddDirective(enableNullable ? PreprocessorDirective.NullableEnable : PreprocessorDirective.NullableDisable);
    }

    public EnumBuilder Open(Action<EnumConfigurationBuilder>? configAction = null)
    {
        return EnumOpen(TypeName, configAction);
    }
}