using Syntaxsmith.CSharp.Configuration;

namespace Syntaxsmith.CSharp;

public class InterfaceBuilder : NamespaceBuilder<InterfaceBuilder>
{
    public InterfaceBuilder(string interfaceName, SyntaxContext context, bool enableNullable = true)
        : base(interfaceName, context)
    {
        AddCommentLine("<autogenerated/>");
        AddDirective(enableNullable ? PreprocessorDirective.NullableEnable : PreprocessorDirective.NullableDisable);
    }

    public InterfaceBuilder Open(Action<InterfaceConfigurationBuilder>? configAction = null)
    {
        return InterfaceOpen(TypeName, configAction);
    }
}