using Syntaxsmith.CSharp.Configuration;

namespace Syntaxsmith.CSharp;

public class StructBuilder : NamespaceBuilder<StructBuilder>
{
    public StructBuilder(string structName, SyntaxContext context, bool enableNullable = true)
        : base(structName, context)
    {
        AddLine("// <autogenerated/>");
        AddLine("#nullable " + (enableNullable ? "enable" : "disable"));

        XmlDocs = new XmlDocsBuilder(Context);
    }

    public XmlDocsBuilder XmlDocs { get; }


    public StructBuilder Open(Action<StructConfigurationBuilder>? configAction = null)
    {
        var builder = new StructConfigurationBuilder(TypeName);

        if (configAction is not null)
        {
            configAction(builder);
        }

        builder.AppendToContext(Context);

        BlockOpen();
        return this;
    }
}