using Syntaxsmith.CSharp.Configuration;

namespace Syntaxsmith.CSharp;

public class StructBuilder : NamespaceBuilder<StructBuilder>
{
    public StructBuilder(string structName, SyntaxContext context, bool enableNullable = true)
        : base(structName, context)
    {
        AddCommentLine("<autogenerated/>");
        AddDirective(enableNullable ? PreprocessorDirective.NullableEnable : PreprocessorDirective.NullableDisable);
    }

    public StructBuilder Open(Action<StructConfigurationBuilder>? configAction = null)
    {
        return StructOpen(TypeName, configAction);
    }
}